apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: dockerpm
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dockerpm
  template:
    metadata:
      labels:
        app: dockerpm
    spec:
      containers:
      - name: dockerpm
        image: sebams/dockerpm:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: mongodb+srv://sebamarambio:sY0rGCZdJevBBiQM@estudio.1agovhf.mongodb.net/Practica?retryWrites=true&w=majority
        imagePullPolicy: Always